In [1]:
# Import numpy package

import numpy as np

In [3]:
# Create a null vector of size 10

null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
# Create a null vector of size 10, but with a fifth value, which is 5

null_vector_fifth = np.zeros(10)
print(null_vector_fifth)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
null_vector_fifth[4] = 5
print(null_vector_fifth)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [8]:
# Create a vector with values ranging from 10 to 49

a = np.arange(10, 50, 1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# Create a 3x3 matrix with values ranging from 0 to 8

m = np.arange(0,9).reshape(3,3) 
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# Find indices of non-zero elements from [1,2,0,0,4,0] 
b = [1,2,0,0,4,0]
c = np.nonzero(b)
print(c)

(array([0, 1, 4]),)


In [23]:
# Create a 3x3 identity matrix 

ident_matr = np.eye(3,3)
print(ident_matr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# Create a 3x3x3 array with random values
np.random.seed(123)
rand_arr = np.random.random((3,3,3))
print(rand_arr)

[[[0.69646919 0.28613933 0.22685145]
  [0.55131477 0.71946897 0.42310646]
  [0.9807642  0.68482974 0.4809319 ]]

 [[0.39211752 0.34317802 0.72904971]
  [0.43857224 0.0596779  0.39804426]
  [0.73799541 0.18249173 0.17545176]]

 [[0.53155137 0.53182759 0.63440096]
  [0.84943179 0.72445532 0.61102351]
  [0.72244338 0.32295891 0.36178866]]]


In [33]:
# Create a 10x10 array with random values and find the minimum and maximum values
np.random.seed(123)
ten_arr = np.random.random((10,10))
print(ten_arr)

np.amin(ten_arr)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
  0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426 0.73799541
  0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338 0.32295891
  0.36178866 0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276 0.4936851  0.42583029 0.31226122
  0.42635131 0.89338916 0.94416002 0.50183668]
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916 0.25045537
  0.48303426 0.98555979 0.51948512 0.61289453]
 [0.12062867 0.8263408  0.60306013 0.54506801 0.34276383 0.30412079
  0.41702221 0.68130077 0.87545684 0.51042234]
 [0.66931378 0.58593655 0.6249035  0.67468905 0.84234244 0.08319499
  0.76368284 0.24366637 0.19422296 0.57245696]
 [0.09571252 0.88532683 0.62724897 0.72341636 0.01612921 0.59443188
  0.55678519 0.15895964 0.15307052 0.69552953]
 [0.31876643 0.6919703  0.55438325 0.38895057 0.92513249 0.84167
  0.35739757 0.

0.01612920669501683

In [34]:
np.amax(ten_arr)

0.9953584820340174

In [35]:
# Create a random vector of size 30 and find the mean value

np.random.seed(123)
rand_vect = np.random.random(30,)
print(rand_vect)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752 0.34317802 0.72904971
 0.43857224 0.0596779  0.39804426 0.73799541 0.18249173 0.17545176
 0.53155137 0.53182759 0.63440096 0.84943179 0.72445532 0.61102351
 0.72244338 0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]


In [36]:
np.mean(rand_vect)

0.4983096481504978

In [66]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

np.random.seed(123)
five_matrix = np.random.random((5,5))
print(five_matrix)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]]


In [68]:
z = ([1,2,3,4])
#np.fill_diagonal(five_matrix[1,], z)
#five_matrix[np.diag_indices_from(five_matrix)] = 0

five_matrix[1,0] = 1
five_matrix[2,1] = 2
five_matrix[3,2] = 3
five_matrix[4,3] = 4

print(five_matrix)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [1.         0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 2.         0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 3.         0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 4.         0.72244338]]


In [69]:
# Normalize a 5x5 random matrix

np.random.seed(123)
rand_matr = np.random.random((5,5))
print(rand_matr)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]]


In [71]:
rand_matr = (rand_matr - rand_matr.min()) / (rand_matr.max() - rand_matr.min())
print(rand_matr)

[[0.69134813 0.24586343 0.18149608 0.53375766 0.71631841]
 [0.39456516 1.         0.67871147 0.45734477 0.36092125]
 [0.30778888 0.72671997 0.41135597 0.         0.36735576]
 [0.73643209 0.13333586 0.12569274 0.51230105 0.51260093]
 [0.62396223 0.85741574 0.72173197 0.59858193 0.71954765]]


In [72]:
# How to find common values between two arrays?

arr1 = ([1,2,3,4])
arr2 = ([3,4,5,6])

np.intersect1d(arr1, arr2)

array([3, 4])

In [76]:
# Create a random vector of size 10 and sort it 

rand_vect_ten = np.random.random(10,)
rand_vect_ten.sort()


print(rand_vect_ten)

[0.30412079 0.41702221 0.51042234 0.58593655 0.6249035  0.66931378
 0.67468905 0.68130077 0.84234244 0.87545684]


In [77]:
# Create random vector of size 10 and replace the maximum value by 0

k = np.random.random(10,)
print(k)

[0.08319499 0.76368284 0.24366637 0.19422296 0.57245696 0.09571252
 0.88532683 0.62724897 0.72341636 0.01612921]


In [79]:
max_matr = np.argmax(k)
print(max_matr)

6


In [80]:
k[6] = 0
print(k)

[0.08319499 0.76368284 0.24366637 0.19422296 0.57245696 0.09571252
 0.         0.62724897 0.72341636 0.01612921]


In [87]:
# Subtract the mean of each row of a matrix

np.random.seed(123)
l = np.random.random((3,4))
print(l)

[[0.69646919 0.28613933 0.22685145 0.55131477]
 [0.71946897 0.42310646 0.9807642  0.68482974]
 [0.4809319  0.39211752 0.34317802 0.72904971]]


In [89]:
n = l - l.mean(axis=1, keepdims=True)
print(n)

[[ 0.2562755  -0.15405435 -0.21334223  0.11112108]
 [ 0.01742663 -0.27893588  0.27872186 -0.0172126 ]
 [-0.00538738 -0.09420177 -0.14314127  0.24273042]]


In [90]:
# How to get the n largest values of an array

f = np.arange(10000)
np.random.shuffle(f)
n = 5


In [93]:
sort_f_ind = np.argsort(f)
sort_f = f[sort_f_ind]
print(sort_f)

[   0    1    2 ... 9997 9998 9999]


In [96]:
larg_f = np.argpartition(sort_f, -5)[-5:]
print(larg_f)

[9995 9996 9997 9998 9999]


In [104]:
# Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

matr_five_three = np.random.randint(0,25, (5,3))
print(matr_five_three)

[[14 18 11]
 [22 19 24]
 [ 2  4 18]
 [ 6 20  8]
 [ 6 17  3]]


In [105]:
np.where(matr_five_three > 4, 0, matr_five_three) # Items larger than 4 are replaced with 0.

array([[0, 0, 0],
       [0, 0, 0],
       [2, 4, 0],
       [0, 0, 0],
       [0, 0, 3]])

In [107]:
np.where(matr_five_three > 4, np.sqrt(matr_five_three), matr_five_three)

array([[3.74165739, 4.24264069, 3.31662479],
       [4.69041576, 4.35889894, 4.89897949],
       [2.        , 4.        , 4.24264069],
       [2.44948974, 4.47213595, 2.82842712],
       [2.44948974, 4.12310563, 3.        ]])